---
- name: Ansible test and play
  hosts: frontend
  become: true
  tasks:
  - name: install dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Copy frontend docker image
    ansible.builtin.copy:
      src: ~/go/src/github.com/loisfa/remote-file-system/docker-images/frontend-1.0.0.tar
      dest: ~/frontend-1.0.0.tar
      owner: vagrant
      group: vagrant
      mode: '0755'

  - name: Load the tar docker image file in docker image collection
    ansible.builtin.shell: docker load < ~/frontend-1.0.0.tar
    args:
      executable: /bin/bash

  - name: Run the docker image
    ansible.builtin.shell: docker run -d -p 8080:5000 loisfa/frontend:1.0.0
    args:
      executable: /bin/bash
